// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgTGG4pS7fIoAXFZb4HSjDlVYogFX7CXg',
    appId: '1:80912346353:web:114709d4e212204e1c0d50',
    messagingSenderId: '80912346353',
    projectId: 'taskmanagement-35291',
    authDomain: 'taskmanagement-35291.firebaseapp.com',
    storageBucket: 'taskmanagement-35291.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW7qzFrMYj5dHF_V1WbcG2k4EAWNnRu0w',
    appId: '1:80912346353:android:2748bcdebfb68cf01c0d50',
    messagingSenderId: '80912346353',
    projectId: 'taskmanagement-35291',
    storageBucket: 'taskmanagement-35291.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAMbJ9MfLcfagCECKk5_vDDrR1mTYP-60',
    appId: '1:80912346353:ios:1fc2919ce9da1c201c0d50',
    messagingSenderId: '80912346353',
    projectId: 'taskmanagement-35291',
    storageBucket: 'taskmanagement-35291.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgTGG4pS7fIoAXFZb4HSjDlVYogFX7CXg',
    appId: '1:80912346353:web:83d85cd80f63218e1c0d50',
    messagingSenderId: '80912346353',
    projectId: 'taskmanagement-35291',
    authDomain: 'taskmanagement-35291.firebaseapp.com',
    storageBucket: 'taskmanagement-35291.firebasestorage.app',
  );
}
